### ISSUE TITLE
Feature requests for giving dnscache-client a higher level

### ISSUE THREAD

**Issue by phantomcraft** [cnmade/dnscache-client#1]
I can see that this project is great even being more like a toy app. It uses the full-featured [miekg](https://github.com/miekg)/[dns](https://github.com/miekg/dns) library and employs LRU cache.

I have some feature suggestions for this project:

1. Ability to choose the IP address and port to listen, and even better, ability to choose multiple addresses for listening as [dnsproxy](https://github.com/AdguardTeam/dnsproxy) does.

2. Ability of choosing (multiple) upstream DNS servers.

3. When choosing DNS servers, ability to specify what transport mechanism the DNS queries will be sent, TCP or UDP.

4. Permanent caching (write the DNS cache to a file): This feature is very relevant and very good as would improve the performance of DNS handling across reboots. Only two projects has this ability, pdnsd and MaraDNS; pdnsd is old and no more developed and has some problems as IPv6 listen point doesn't work with it and there is no way to specify the port of the upstream DNS server; MaraDNS has similar problems; there is also [SmartDNS](https://github.com/pymumu/smartdns) which does something similar but it has no support for DNSSEC.

==================

@cnmade 

I hope you consider my suggestions.

Thanks.

**Comment by cnmade** [comment]
Yes, thanks for advice, I have a new project to cover all your needs. more or less.
https://github.com/godnsproxy/godnsproxy

**Comment by phantomcraft** [comment]
@cnmade 

A fork of dnsproxy, yes, good idea.

All the suggestions I made are already implemented in dnsproxy and its forks except by the permanent caching.

When I you have a spare time I suggest you to implement this feature because it would be overkill.

**Comment by phantomcraft** [comment]
I discovered that [Knot Resolver](https://github.com/CZ-NIC/knot-resolver) does all the suggestions I made and I'm using right now. I was searching for permanent cache mainly, I bookmarked your project [godnsproxy](https://github.com/godnsproxy/godnsproxy) to see if this feature will be implemented in the future.

Thanks, closing.
